contacts/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from profile import views as prof_views

urlpatterns = [
    path('', prof_views.home, name='home'),
    path('account/', prof_views.account, name='account'),
    path(
        'account/',
        include([
            path('login/', prof_views.LoginView.as_view(), name='login'),
            path('', include('django.contrib.auth.urls'))
        ]),
    ),
    path('account/register/', prof_views.register, name='register'),
    path(
        'content/',
        include([
            path('', prof_views.user_content_view, name='content'),
            path('new/', prof_views.add_item, name='add_item'),
            path(  # for single models like Email or WorkExperience
                '<slug:model_name>/',
                include([
                    path('new/', prof_views.ContentCreateUpdateView.as_view(), name='item_create'),
                    path('<int:content_pk>/', prof_views.ContentCreateUpdateView.as_view(), name='item_update'),
                    path('<int:content_pk>/delete/', prof_views.content_delete, name='item_delete'),
                ])
            ),
        ]),
    ),
    path('shared/<uuid:uid>/', prof_views.SharedProfileView.as_view(), name='shared_profile'),
    path(
        'connections/',
        include([
            path('', prof_views.ConnectionListView.as_view(), name='connection_list'),
            path('declined/', prof_views.DeclinedListView.as_view(), name='declined_list'),
            path('<int:connection_pk>/', prof_views.connection, name='connection'),
            path('<int:request_pk>/accept/', prof_views.connection_accept, name='connection_accept'),
            path('<int:request_pk>/decline/', prof_views.connection_decline, name='connection_decline'),
        ])
    ),

    path('admin/', admin.site.urls),
    path('profile/', include('profile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.profile_list, name='profile_list'),
    path('new/', views.ProfileCreateUpdateView.as_view(), {'next': 'profile'}, name='profile_create'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('content/<int:related_content_pk>/order', views.ContentOrderView.as_view(), name='attachment_order'),
    path(
        'edit/<int:profile_pk>/',
        views.ProfileCreateUpdateView.as_view(),
        {'next': 'profile_list'},
        name='list_profile_edit'
    ),
    # consider [Sqids](https://sqids.org/) instead of pks
    path(
        '<int:profile_pk>/',
        include([
            path('', views.profile, name='profile'),
            path('edit/', views.ProfileCreateUpdateView.as_view(), {'next': 'profile'}, name='profile_edit'),
            path('delete/', views.profile_delete, name='profile_delete'),
            path('select/', views.ProfileSelectContentView.as_view(), name='profile_content_select', ),
            path('editdetail/', views.ProfileDetailEditView.as_view(), name='profile_detail_edit'),
            path('img/', views.update_profile_img, name='update_profile_img'),
            path('img/delete/', views.profile_img_delete, name='profile_img_delete'),
            path(
                'share/',
                include([
                    path('', views.share, name='share'),
                    path('<int:link_pk>/', views.share, name='link_share'),
                    path(
                        'links/',
                        include([
                            path('', views.profile_links, name='profile_links'),
                            path('new/', views.ProfileCreateLink.as_view(), name='profile_link_create'),
                            path('<pk>/', views.ProfileLinkDetail.as_view(), name='profile_link_detail'),
                            path('<pk>/delete/', views.profile_link_delete, name='profile_link_delete'),
                        ]),
                    ),
                ]),
            ),
            path(
                '<int:content_pk>/',
                include([
                    path('select/', views.ProfileSelectContentView.as_view(), name='content_content_select'),
                    path('delete/', views.content_delete, name='content_content_delete'),
                ])
            ),
            path(
                '<slug:model_name>/',
                include([
                    path('new/', views.ContentCreateUpdateView.as_view(), name='profile_content_create'),
                    path('<int:content_pk>/', views.ContentCreateUpdateView.as_view(), name='profile_content_update'),
                    path('<int:content_pk>/delete/', views.content_delete, name='profile_content_delete'),
                ]),
            ),
        ]),
    ),
    path(
        'links/',
        include([
            path('', views.profile_links, name='link_list'),
            path('<pk>/', views.ProfileLinkDetail.as_view(), name='link_detail'),
        ])
    ),

    # path('', views.profile_list, name='profile_list'),
    # path('<slug:slug>/', views.profile, name='profile'),
    # path('<slug:slug>/edit/', views.EditCardView.as_view(), name='edit'),

    # path('share/', views.share_card, name='share'),
    # path('share/<uuid:share_uuid>/', views.view_shared_profile, name='shared_profile'),
    # path('share/<uuid:share_uuid>/connect/', views.connect, name='connect'),

    # path('download/', views.download_card, name='download_card'),
    # path('connections/', views.connection_list, name='connection_list'),
    # path('connections/<uuid:connection_id>/', views.connection_detail, name='connection_detail'),
    # path('contactbook/', views.contact_book, name='contact_book'),
    # path('contactbook/import', views.import_cards, name='import_cards'),
    # path('contactbook/<int:card_id>', views.card_detail, name='card_detail'),
    # path('connections/edit/', views.edit_connection, name='edit_connection'),
    # path('connections/edit/<uuid:connection_id>/', views.edit_connection, name='edit_connection'),
    # path('connections/download/<uuid:connection_id>/', views.download_card, name='download_connection_card')
]

profile/models.py
import uuid
import os.path
import vobject
import datetime as dt
from urllib.parse import urlparse

from .fields import OrderField
from .utils import consts, vcard

from django.apps import apps
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models import Value
from django.http import HttpResponse
from django.utils.text import slugify
from embed_video.fields import EmbedVideoField
from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _
from djangoyearlessdate.models import YearlessDateField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation


class Profile(models.Model):
    class Kind(models.TextChoices):
        INDIVIDUAL = 'ID', _('Individual')

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    # individual, group, org...
    kind = models.CharField(
        max_length=2,
        choices=Kind,
        default=Kind.INDIVIDUAL,
        blank=False,
        verbose_name='kind',
    )

    # -------- local info for the user --------
    title = models.CharField(max_length=50, blank=False, verbose_name='kind')
    description = models.CharField(blank=True, verbose_name='description')

    # -------- info displayed on profile --------
    # todo: update for non-individual self.kind
    prefix = models.CharField(max_length=50, blank=True, verbose_name='prefix')
    first_name = models.CharField(max_length=50, blank=True, verbose_name='first name')
    middle_name = models.CharField(max_length=50, blank=True, verbose_name='middle name')
    # last name serves as name if kind is not individual
    last_name = models.CharField(max_length=50, blank=True, verbose_name='last name')
    suffix = models.CharField(max_length=50, blank=True, verbose_name='suffix')
    nickname = models.CharField(max_length=50, blank=True, verbose_name='nickname')

    photo = models.ImageField(
        upload_to=consts.PROFILE_PHOTO_DIR,
        blank=True,
        verbose_name='photo',
    )

    headline = models.CharField(max_length=120, blank=True, verbose_name='headline')
    location = models.CharField(max_length=50, blank=True, verbose_name='location')
    about = models.TextField(blank=True, verbose_name='about')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return f'{self.user.username}\'s {self.title} Profile'

    def get_absolute_url(self):
        return reverse('profile', kwargs={'profile_pk': self.pk})

    @property
    def fn(self):
        s = (f'{self.prefix + " " if self.prefix else ""}'
             f'{self.first_name + " " if self.first_name else ""}'
             f'{self.middle_name + " " if self.middle_name else ""}'
             f'{self.last_name}'
             f'{", " + self.suffix if self.suffix else ""}')
        return s


class Content(models.Model):
    profile = models.ForeignKey(
        Profile,
        related_name='contents',
        related_query_name='content',
        on_delete=models.CASCADE,
    )

    def item_subclass_choices(self):
        return [m.__name__ for m in apps.get_models() if issubclass(m, ItemBase)]

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={
            'model__in': item_subclass_choices()
        }
    )
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['profile'])

    class Meta:
        ordering = ['order']
        verbose_name = 'content'
        verbose_name_plural = 'contents'


class ItemBase(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='%(class)s_related',
        on_delete=models.CASCADE,
    )
    content_related = GenericRelation(Content)
    label = models.CharField(max_length=50, blank=True, verbose_name='label')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def render(self):
        return render_to_string(
            f'profile/partials/models/{self.__class__.__name__.lower()}_render.html',
            {'object': self}
        )


# todo: validate all Items
class ContactInfoBase(ItemBase):
    class InfoTypes(models.TextChoices):
        WORK = 'W', _('Work')
        HOME = 'H', _('Home')
        OTHER = 'O', _('Other')

    info_type = models.CharField(
        max_length=1,
        choices=InfoTypes,
        blank=True,
        verbose_name='type',
    )

    class Meta(ItemBase.Meta):
        abstract = True


class Email(ContactInfoBase):
    email_address = models.EmailField(
        blank=False,
        verbose_name='email',
    )

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'email'
        verbose_name_plural = 'emails'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.email_address}'
                f'{", " + self.label if self.label else ""}')


class Phone(ContactInfoBase):
    # todo: international?
    phone_number = PhoneNumberField(
        balnk=False,
        verbose_name='phone number',
    )

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'phone'
        verbose_name_plural = 'phones'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.phone_number}'
                f'{", " + self.label if self.label else ""}')


class Address(ContactInfoBase):
    # todo: international?
    street1 = models.CharField(blank=False, verbose_name='street')
    street2 = models.CharField(blank=True, verbose_name='street line 2')
    city = models.CharField(blank=False, verbose_name='city')
    state = models.CharField(blank=False, verbose_name='state')
    zip = models.CharField(max_length=10, blank=False, verbose_name='zip code')
    country = models.CharField(blank=True, verbose_name='country')

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'address'
        verbose_name_plural = 'addresses'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.street1}'
                f'{", " + self.label if self.label else ""}')


class LinkBase(models.Model):
    """holds primary domains and info for external links
    E.g. netloc: https://github.com/"""
    title = models.CharField(
        blank=False,
        default='Website',
        verbose_name='title',
    )
    netloc = models.CharField(
        blank=True,
        verbose_name='netloc',
    )

    class Meta:
        verbose_name = 'linkbase'
        verbose_name_plural = 'linkbases'

    def __str__(self):
        return str(self.title)


class Link(ItemBase):
    linkbase = models.ForeignKey(
        LinkBase,
        default=1,
        on_delete=models.SET_DEFAULT,
        verbose_name='linkbase',
        related_name='links',
        related_query_name='link',
    )
    url = models.CharField(max_length=200, verbose_name='url')
    is_independent_url = models.BooleanField(
        default=True,
        blank=False,
        verbose_name='independent url',
        help_text='Indicates url does not require linkbase.netlock as the prefix',
    )

    class Meta(ItemBase.Meta):
        ordering = ['linkbase']
        verbose_name = 'link'
        verbose_name_plural = 'links'

    def __str__(self):
        if self.is_independent_url:
            return str(self.url)
        else:
            return f'{self.linkbase.domain}{self.url}'

    def save(self, *args, **kwargs):
        if not self.is_independent_url:
            self.is_independent_url = self.linkbase == 1
        super().save(*args, **kwargs)

    @property
    def pretty_url(self):
        if self.is_independent_url:
            url = urlparse(str(self.url))
        else:
            url = urlparse(f'{self.linkbase.domain}{self.url}')
        return f'{url.netloc}{url.path}{url.params}{url.query}{url.fragment}'.rstrip('/')


class Attachment(ItemBase):
    class AttachmentTypes(models.TextChoices):
        DOCUMENT = 'D', _('Document')
        IMAGE = 'I', _('Image')

    attachment_type = models.CharField(
        max_length=1,
        choices=AttachmentTypes,
        blank=False,
        verbose_name='attachment type',
    )
    url = models.URLField(
        blank=True,
        verbose_name='url',
    )
    file = models.FileField(
        upload_to=consts.ATTACHMENT_MODEL_DIR,
        blank=True,
        verbose_name='file',
    )

    def __str__(self):
        return (f'{self.attachment_type.label}: '
                f'{self.url if self.url else self.file.name}')


class PostBase(ItemBase):
    title = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='title',
    )
    description = models.TextField(
        blank=True,
        verbose_name='description',
    )
    date = models.DateField(
        blank=True,
        verbose_name='date',
    )
    external_link = models.URLField(
        blank=True,
        verbose_name='external link',
    )

    class Meta(ItemBase.Meta):
        abstract = True
        ordering = ['-date']

    def __str__(self):
        return f'{self.title}{" - " + str(self.date) if self.date else ""}'


class OrgBase(PostBase):
    organization = models.CharField(
        max_length=200,
        blank=True,
        verbose_name='organization',
    )

    class Meta(PostBase.Meta):
        abstract = True

profile/models/tag.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from . import profile as profile_models


class TagBase(profile_models.ItemBase):
    class Meta(profile_models.ItemBase.Meta):
        abstract = True

    def __str__(self):
        return str(self.label)


class Skill(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='skill',
    )


class Interest(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='interest',
    )


class Cause(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='cause',
    )
    external_link = models.URLField(
        blank=True,
        verbose_name='external link',
    )

profile/templates/profile/account.html
{% extends "base.html" %}
{% load static %}

{% block title %}Your Account{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header">
    Your Account
  </div>
  <div class="card-body">
    <p class="card-text mb-3">
      <span class="fw-bold">Username: </span>
      {{ user.username }}
    </p>
    <p class="card-text mb-3">
      <span class="fw-bold">Joined: </span>
      {{ user.date_joined|date:"F d, Y" }}
    </p>
    <p id="current-email" class="card-text mb-3">
      <span class="fw-bold">Primary email: </span>
      {{ user.email }}
      <button id="edit-email-button" class="badge btn btn-secondary" type="button">Update</button>
    </p>
    <div id="edit-email-form" class="card-text mb-3" hidden>
      <form method="post" id="form-container">
        <div class="row">
          <div class="fw-bold col-auto">Primary email: </div>
          <div class="col-auto">{{ user_form.email }}</div>
          {% csrf_token %}
          <div class="col-auto">
            <input type="submit" class="btn btn-primary" value="Save">
          </div>
        </div>
      </form>
    </div>
    <p class="card-text mb-3">
      <a class="badge btn btn-secondary" href="{% url 'password_change' %}">Change Password</a>
    </p>
  </div>
</div>

<script src="{% static 'js/edit_primary_email.js' %}"></script>
{% endblock %}

profile/templates/profile/card.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}

{% block title %}{{ profile.title }} | Profile{% endblock %}

{% block content %}

{% if entity == 'self' %}
{# from bootstrap https://htmx.org/examples/modal-bootstrap/ #}
{# share profile modal and update image #}
<div id="modals-here"
    class="modal modal-blur fade"
    style="display: none"
    aria-hidden="false"
    tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<div id="update-img-model"
    class="modal modal-blur fade"
    style="display: none"
    aria-hidden="false"
    tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content"></div>
    </div>
</div>
{% endif %}

{% if entity == "shared" %}
<div class="container mb-3">
  {% if request.user.is_authenticated %}
  {% with suuid=p.share_uuid %}
  <form action="{{ request.build_absolute_uri }}connect/" method="post">
    <button class="btn btn-outline-primary" type="submit">Connect</button>
    {% csrf_token %}
  </form>
  {% endwith %}
  {% else %}
  <p>
    <a href="{% url 'login' %}?next={{ profile.get_shareable_url }}">Log-in</a>
    or <a href="{% url 'register' %}">create an account</a> to connect with
    {{ vc.n.value.given|default:vc.fn}}.
  </p>
  {% endif %}
</div>
{% endif %}

<div class="container p-3 mb-3 d-md-flex border-bottom">
  <div class="me-5 mb-3 d-flex flex-column">
    <div class="position-relative">
      {% with profimg=profile.card.photo %}
      {% thumbnail profimg "200x200" crop="center" as im %}
      <img id="PHOTO" class="rounded" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ profile.card.FN }} profile photo">
      {% empty %}
      <svg class="rounded" width="200" height="200" xmlns="http://www.w3.org/2000/svg">
        <rect width="200" height="200" fill="gray" />
      </svg>
      {% endthumbnail %}
      {% if entity == "self" or entity == "connection" %}
      <span class="position-absolute top-0 start-0 dropdown">
        <button type="button" class="btn btn-light border border-dark pt-0 pb-1" data-bs-toggle="dropdown" aria-expanded="false">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
            <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3"></path>
          </svg>
        </button>
        <ul class="dropdown-menu">
          <li>
            <button
              hx-get="{{ profile.get_absolute_url }}edit/profileimg/"
              hx-target="#update-img-model"
              hx-trigger="click"
              data-bs-toggle="modal"
              data-bs-target="#update-img-model"
              class="dropdown-item">
              {% if profimg %}
              Update
              {% else %}
              Upload Image
              {% endif %}
            </button>
          </li>
          {% if profimg %}
          <li>
            <form method="post" onsubmit="return confirm('Are you sure you wish to delete your profile picture?');">
              <input type="hidden" name="delete-profile-img" value="true" id="delete-profile-img" />
              <button class="dropdown-item btn btn-link link-danger" type="submit" value="deleted">Delete</button>
              {% csrf_token %}
            </form>
          </li>
          {% endif %}
        </ul>
      </span>
      {% endif %}
      {% endwith %}
    </div>
  </div>

  <div class="justify-content-left flex-wrap">
    <div id="FN" class="fs-2 fw-bold mb-0">{{ vc.fn.value }}</div>

    {% with headline=profile.headline %}
    {% if headline %}
    <p id="headline" class="card-text mb-2">{{ headline }}</p>
    {% endif %}
    {% endwith %}

    {% with nick=vc.nickname.value loc=profile.location %}
    {% if nick or loc %}
    <div class="d-flex justify-content-start mb-4">
      {% if loc %}
      <div id="location" class="fs-6 text-muted">{{ loc }}</div>
      {% endif %}

      {% if nick and loc %}
      <div class="fs-6 text-muted mx-2"> &#x2022; </div>
      {% endif %}

      {% if nick %}
      <div id="NICKNAME" class="fs-6 text-muted">"{{ nick }}"</div>
      {% endif %}
    </div>
    {% endif %}
    {% endwith %}

    {% with description=profile.about %}
    {% if description %}
    <p class="d-flex flex-wrap border-top pt-3">
      {{ description }}
    </p>
    {% endif %}
    {% endwith %}
  </div>
</div>

{% if entity == "self" or entity == "connection" %}
<div class="container mb-3 d-inline-flex">
  {% if entity == "self" %}
  <button
    hx-get="{% url 'share' %}"
    hx-target="#modals-here"
    hx-trigger="click"
    data-bs-toggle="modal"
    data-bs-target="#modals-here"
    class="btn btn-dark me-3">Share</button>
  <a class="btn btn-dark me-3" href="{% url 'download_card' %}">Download</a>
  {% endif %}
  {# <a class="btn btn-dark me-3" href="{% url 'edit' %}">Edit</a> #}
  <a class="btn btn-dark me-3" href="{{ profile.get_absolute_url }}edit/">Edit</a>
</div>
{% endif %}

<div class="container mb-3">
  {% with kind=vc.kind.value %}
  {% if kind != "Individual" %}
  <p><i>{{ vc.kind.value }}</i></p>
  {% endif %}
  {% endwith %}

  {% with phones=vc.tel_list %}
  {% if phones %}
  <div class="card mb-3">
    <div class="card-header">
      Phone
    </div>
    <ul id="TEL" class="list-group list-group-flush">
      {% for phone in phones %}
      <!-- todo: does phone.phone_type return the key or value? -->
      <li class="{{ phone.type_paramlist|join:' ' }} list-group-item">
        <span class="text-muted">{{ phone.type_paramlist|join:', ' }}</span>
        {{ phone.value }}
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  {% endwith %}

  {% with emails=vc.email_list %}
  {% if emails %}
  <div class="card mb-3">
    <div class="card-header">
      Email
    </div>
    <ul id="EMAIL" class="list-group list-group-flush">
      {% for email in emails %}
      <li class="list-group-item">
        {% with emailtypes=email.type_paramlist %}
        {% if emailtypes %}
        <span class="text-muted">
          {% for et in emailtypes %}
          {% if et != 'INTERNET' %}{{ et }} {% endif %}
          {% endfor %}
        </span>
        {% endif %}
        {% endwith %}
        <a href="mailto:{{ email.value }}" class="{{ email.type_paramlist|join:' ' }}">{{ email.value }}</a>
      </li>
      <!-- TODO: protect mailto links -->
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  {% endwith %}

  {% with urls=vc.url_list %}
  {% if urls %}
  <div class="card mb-3">
    <div class="card-header">
      Links
    </div>
    <ul id="URL" class="list-group list-group-flush">
      {% for url in urls %}
      <li class="list-group-item">
        {% with urltype=url.type_paramlist %}
        {% if urltype %}
        <span class="text-muted">
          {{ urltype|join:', ' }}
        </span>
        {% endif %}
        {% endwith %}
        <a href="{{ url.value }}" class="{{ url.type_paramlist|join:' ' }}" target="_blank">
          {{ url.value }}
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  {% endwith %}

  {% with addresses=vc.adr_list %}
  {% if addresses %}
  <div class="card mb-3">
    <div class="card-header">
      Mailing
    </div>
    <ul id="ADR" class="list-group list-group-flush">
      {% for address in addresses %}
      <li class="list-group-item {{ address.type_paramlist|join:' ' }}">
        <div class="d-md-flex">
          <div class="me-3">
            <p class="text-muted">{{ address.type_paramlist|join:', ' }}</p>
          </div>
          <div class="justify-content-left flex-wrap">
            {{ address.value.street }}<br>
            {{ address.value.city }}, {{ address.value.region }} {{ address.value.code }}<br>
            {% if address.value.country %}{{ address.value.country }}{% endif %}
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  {% endwith %}

  <!-- todo: add org logo -->
  {% with titles=vc.title_list roles=vc.role_list orgs=vc.org_list %}
  {% if titles or roles or orgs %}
  <div class="card mb-3">
    <div class="card-header">
      Organizational
    </div>
    <div class="card-body">
      {% if orgs %}
      <h5 class="card-title">Organizations</h5>
      <ul class="card-text">
        {% for org in orgs %}
        {% for o in org.value %}
        <li>{{ o }}</li>
        {% endfor %}
        {% endfor %}
      </ul>
      {% endif %}

      {% if titles %}
      <h5 class="card-title">Titles</h5>
      <ul class="card-text">
        {% for title in titles %}
        <li>{{ title.value }}</li>
        {% endfor %}
      </ul>
      {% endif %}

      {% if roles %}
      <h5 class="card-title">Roles</h5>
      <ul class="card-text">
        {% for role in roles %}
        <li>{{ role.value }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
  </div>
  {% endif %}
  {% endwith %}


  {% with bday=vc.bday_list anniv=vc.anniversary_list %}
  {% if bday or anniv or sex or gender %}
  <div class="card mb-3">
    <div class="card-header">
      Personal
    </div>
    <div class="card-body">
      {% if bday %}
      {% for b in bday %}
      <p id="BDAY" class="card-text">
        <span class="fw-bold">Birthday: </span>
        {{ b.value }}
      </p>
      {% endfor %}
      {% endif %}

      {% if anniv %}
      {% for a in anniv %}
      <p id="ANNIVERARY" class="card-text">
        <span class="fw-bold">Anniversary: </span>
        {{ a.value }}
      </p>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  {% endif %}
  {% endwith %}

  {% with tags=vc.categories_list %}
  {% if tags %}
  <div class="card mb-3">
    <div class="card-header">
      Tags
    </div>
    <div id="CATEGORIES" class="card-body">
      {% for taglist in tags %}
      <p class="card-text">{% for tag in taglist.value %}<a href="#" class="{{ tag }}">#{{ tag }}</a> {% endfor %}</p>
      {% endfor %}
    </div>
  </div>
  {% endif %}
  {% endwith %}

  {% with notes=vc.note_list %}
  {% if notes %}
  <div class="card mb-3">
    <div class="card-header">
      Notes
    </div>
    <div class="card-body">
      {% for note in notes %}
      <p class="card-text">{{ note.value }}</p>
      {% endfor %}
    </div>
  </div>
  {% endif %}
  {% endwith %}

</div>

{% endblock %}

profile/templates/profile/dne.html
{% extends 'base.html' %}

{% block content %}
<p>Looks like that profile does not exists or the link to it has expired.</p>
{% endblock %}