contacts/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from profile import views as prof_views

urlpatterns = [
    path('', prof_views.home, name='home'),
    path('account/', prof_views.account, name='account'),
    path(
        'account/',
        include([
            path('login/', prof_views.LoginView.as_view(), name='login'),
            path('', include('django.contrib.auth.urls'))
        ]),
    ),
    path('account/register/', prof_views.register, name='register'),
    path(
        'content/',
        include([
            path('', prof_views.user_content_view, name='content'),
            path('new/', prof_views.add_item, name='add_item'),
            path(  # for single models like Email or WorkExperience
                '<slug:model_name>/',
                include([
                    path('new/', prof_views.ContentCreateUpdateView.as_view(), name='item_create'),
                    path('<int:content_pk>/', prof_views.ContentCreateUpdateView.as_view(), name='item_update'),
                    path('<int:content_pk>/delete/', prof_views.content_delete, name='item_delete'),
                ])
            ),
        ]),
    ),
    path('shared/<uuid:uid>/', prof_views.SharedProfileView.as_view(), name='shared_profile'),
    path(
        'connections/',
        include([
            path('', prof_views.ConnectionListView.as_view(), name='connection_list'),
            path('declined/', prof_views.DeclinedListView.as_view(), name='declined_list'),
            path('<int:connection_pk>/', prof_views.connection, name='connection'),
            path('<int:request_pk>/accept/', prof_views.connection_accept, name='connection_accept'),
            path('<int:request_pk>/decline/', prof_views.connection_decline, name='connection_decline'),
        ])
    ),

    path('admin/', admin.site.urls),
    path('profile/', include('profile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.profile_list, name='profile_list'),
    path('new/', views.ProfileCreateUpdateView.as_view(), {'next': 'profile'}, name='profile_create'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('content/<int:related_content_pk>/order', views.ContentOrderView.as_view(), name='attachment_order'),
    path(
        'edit/<int:profile_pk>/',
        views.ProfileCreateUpdateView.as_view(),
        {'next': 'profile_list'},
        name='list_profile_edit'
    ),
    # consider [Sqids](https://sqids.org/) instead of pks
    path(
        '<int:profile_pk>/',
        include([
            path('', views.profile, name='profile'),
            path('edit/', views.ProfileCreateUpdateView.as_view(), {'next': 'profile'}, name='profile_edit'),
            path('delete/', views.profile_delete, name='profile_delete'),
            path('select/', views.ProfileSelectContentView.as_view(), name='profile_content_select', ),
            path('editdetail/', views.ProfileDetailEditView.as_view(), name='profile_detail_edit'),
            path('img/', views.update_profile_img, name='update_profile_img'),
            path('img/delete/', views.profile_img_delete, name='profile_img_delete'),
            path(
                'share/',
                include([
                    path('', views.share, name='share'),
                    path('<int:link_pk>/', views.share, name='link_share'),
                    path(
                        'links/',
                        include([
                            path('', views.profile_links, name='profile_links'),
                            path('new/', views.ProfileCreateLink.as_view(), name='profile_link_create'),
                            path('<pk>/', views.ProfileLinkDetail.as_view(), name='profile_link_detail'),
                            path('<pk>/delete/', views.profile_link_delete, name='profile_link_delete'),
                        ]),
                    ),
                ]),
            ),
            path(
                '<int:content_pk>/',
                include([
                    path('select/', views.ProfileSelectContentView.as_view(), name='content_content_select'),
                    path('delete/', views.content_delete, name='content_content_delete'),
                ])
            ),
            path(
                '<slug:model_name>/',
                include([
                    path('new/', views.ContentCreateUpdateView.as_view(), name='profile_content_create'),
                    path('<int:content_pk>/', views.ContentCreateUpdateView.as_view(), name='profile_content_update'),
                    path('<int:content_pk>/delete/', views.content_delete, name='profile_content_delete'),
                ]),
            ),
        ]),
    ),
    path(
        'links/',
        include([
            path('', views.profile_links, name='link_list'),
            path('<pk>/', views.ProfileLinkDetail.as_view(), name='link_detail'),
        ])
    ),

    # path('', views.profile_list, name='profile_list'),
    # path('<slug:slug>/', views.profile, name='profile'),
    # path('<slug:slug>/edit/', views.EditCardView.as_view(), name='edit'),

    # path('share/', views.share_card, name='share'),
    # path('share/<uuid:share_uuid>/', views.view_shared_profile, name='shared_profile'),
    # path('share/<uuid:share_uuid>/connect/', views.connect, name='connect'),

    # path('download/', views.download_card, name='download_card'),
    # path('connections/', views.connection_list, name='connection_list'),
    # path('connections/<uuid:connection_id>/', views.connection_detail, name='connection_detail'),
    # path('contactbook/', views.contact_book, name='contact_book'),
    # path('contactbook/import', views.import_cards, name='import_cards'),
    # path('contactbook/<int:card_id>', views.card_detail, name='card_detail'),
    # path('connections/edit/', views.edit_connection, name='edit_connection'),
    # path('connections/edit/<uuid:connection_id>/', views.edit_connection, name='edit_connection'),
    # path('connections/download/<uuid:connection_id>/', views.download_card, name='download_connection_card')
]

profile/models.py
import uuid
import os.path
import vobject
import datetime as dt
from urllib.parse import urlparse

from .fields import OrderField
from .utils import consts, vcard

from django.apps import apps
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models import Value
from django.http import HttpResponse
from django.utils.text import slugify
from embed_video.fields import EmbedVideoField
from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _
from djangoyearlessdate.models import YearlessDateField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation


class Profile(models.Model):
    class Kind(models.TextChoices):
        INDIVIDUAL = 'ID', _('Individual')

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    # individual, group, org...
    kind = models.CharField(
        max_length=2,
        choices=Kind,
        default=Kind.INDIVIDUAL,
        blank=False,
        verbose_name='kind',
    )

    # -------- local info for the user --------
    title = models.CharField(max_length=50, blank=False, verbose_name='kind')
    description = models.CharField(blank=True, verbose_name='description')

    # -------- info displayed on profile --------
    # todo: update for non-individual self.kind
    prefix = models.CharField(max_length=50, blank=True, verbose_name='prefix')
    first_name = models.CharField(max_length=50, blank=True, verbose_name='first name')
    middle_name = models.CharField(max_length=50, blank=True, verbose_name='middle name')
    # last name serves as name if kind is not individual
    last_name = models.CharField(max_length=50, blank=True, verbose_name='last name')
    suffix = models.CharField(max_length=50, blank=True, verbose_name='suffix')
    nickname = models.CharField(max_length=50, blank=True, verbose_name='nickname')

    photo = models.ImageField(
        upload_to=consts.PROFILE_PHOTO_DIR,
        blank=True,
        verbose_name='photo',
    )

    headline = models.CharField(max_length=120, blank=True, verbose_name='headline')
    location = models.CharField(max_length=50, blank=True, verbose_name='location')
    about = models.TextField(blank=True, verbose_name='about')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return f'{self.user.username}\'s {self.title} Profile'

    def get_absolute_url(self):
        return reverse('profile', kwargs={'profile_pk': self.pk})

    @property
    def fn(self):
        s = (f'{self.prefix + " " if self.prefix else ""}'
             f'{self.first_name + " " if self.first_name else ""}'
             f'{self.middle_name + " " if self.middle_name else ""}'
             f'{self.last_name}'
             f'{", " + self.suffix if self.suffix else ""}')
        return s


class Content(models.Model):
    profile = models.ForeignKey(
        Profile,
        related_name='contents',
        related_query_name='content',
        on_delete=models.CASCADE,
    )

    def item_subclass_choices(self):
        return [m.__name__ for m in apps.get_models() if issubclass(m, ItemBase)]

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={
            'model__in': item_subclass_choices()
        }
    )
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['profile'])

    class Meta:
        ordering = ['order']
        verbose_name = 'content'
        verbose_name_plural = 'contents'


class ItemBase(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='%(class)s_related',
        on_delete=models.CASCADE,
    )
    content_related = GenericRelation(Content)
    label = models.CharField(max_length=50, blank=True, verbose_name='label')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def render(self):
        return render_to_string(
            f'profile/partials/models/{self.__class__.__name__.lower()}_render.html',
            {'object': self}
        )


# todo: validate all Items
class ContactInfoBase(ItemBase):
    class InfoTypes(models.TextChoices):
        WORK = 'W', _('Work')
        HOME = 'H', _('Home')
        OTHER = 'O', _('Other')

    info_type = models.CharField(
        max_length=1,
        choices=InfoTypes,
        blank=True,
        verbose_name='type',
    )

    class Meta(ItemBase.Meta):
        abstract = True


class Email(ContactInfoBase):
    email_address = models.EmailField(
        blank=False,
        verbose_name='email',
    )

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'email'
        verbose_name_plural = 'emails'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.email_address}'
                f'{", " + self.label if self.label else ""}')


class Phone(ContactInfoBase):
    # todo: international?
    phone_number = PhoneNumberField(
        balnk=False,
        verbose_name='phone number',
    )

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'phone'
        verbose_name_plural = 'phones'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.phone_number}'
                f'{", " + self.label if self.label else ""}')


class Address(ContactInfoBase):
    # todo: international?
    street1 = models.CharField(blank=False, verbose_name='street')
    street2 = models.CharField(blank=True, verbose_name='street line 2')
    city = models.CharField(blank=False, verbose_name='city')
    state = models.CharField(blank=False, verbose_name='state')
    zip = models.CharField(max_length=10, blank=False, verbose_name='zip code')
    country = models.CharField(blank=True, verbose_name='country')

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'address'
        verbose_name_plural = 'addresses'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.street1}'
                f'{", " + self.label if self.label else ""}')


class LinkBase(models.Model):
    """holds primary domains and info for external links
    E.g. netloc: https://github.com/"""
    title = models.CharField(
        blank=False,
        default='Website',
        verbose_name='title',
    )
    netloc = models.CharField(
        blank=True,
        verbose_name='netloc',
    )

    class Meta:
        verbose_name = 'linkbase'
        verbose_name_plural = 'linkbases'

    def __str__(self):
        return str(self.title)


class Link(ItemBase):
    linkbase = models.ForeignKey(
        LinkBase,
        default=1,
        on_delete=models.SET_DEFAULT,
        verbose_name='linkbase',
        related_name='links',
        related_query_name='link',
    )
    url = models.CharField(max_length=200, verbose_name='url')
    is_independent_url = models.BooleanField(
        default=True,
        blank=False,
        verbose_name='independent url',
        help_text='Indicates url does not require linkbase.netlock as the prefix',
    )

    class Meta(ItemBase.Meta):
        ordering = ['linkbase']
        verbose_name = 'link'
        verbose_name_plural = 'links'

    def __str__(self):
        if self.is_independent_url:
            return str(self.url)
        else:
            return f'{self.linkbase.domain}{self.url}'

    def save(self, *args, **kwargs):
        if not self.is_independent_url:
            self.is_independent_url = self.linkbase == 1
        super().save(*args, **kwargs)

    @property
    def pretty_url(self):
        if self.is_independent_url:
            url = urlparse(str(self.url))
        else:
            url = urlparse(f'{self.linkbase.domain}{self.url}')
        return f'{url.netloc}{url.path}{url.params}{url.query}{url.fragment}'.rstrip('/')


class Attachment(ItemBase):
    class AttachmentTypes(models.TextChoices):
        DOCUMENT = 'D', _('Document')
        IMAGE = 'I', _('Image')

    attachment_type = models.CharField(
        max_length=1,
        choices=AttachmentTypes,
        blank=False,
        verbose_name='attachment type',
    )
    url = models.URLField(
        blank=True,
        verbose_name='url',
    )
    file = models.FileField(
        upload_to=consts.ATTACHMENT_MODEL_DIR,
        blank=True,
        verbose_name='file',
    )

    def __str__(self):
        return (f'{self.attachment_type.label}: '
                f'{self.url if self.url else self.file.name}')


class PostBase(ItemBase):
    title = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='title',
    )
    description = models.TextField(
        blank=True,
        verbose_name='description',
    )
    date = models.DateField(
        blank=True,
        verbose_name='date',
    )
    external_link = models.URLField(
        blank=True,
        verbose_name='external link',
    )

    class Meta(ItemBase.Meta):
        abstract = True
        ordering = ['-date']

    def __str__(self):
        return f'{self.title}{" - " + str(self.date) if self.date else ""}'


class OrgBase(PostBase):
    organization = models.CharField(
        max_length=200,
        blank=True,
        verbose_name='organization',
    )

    class Meta(PostBase.Meta):
        abstract = True

profile/models/tag.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from . import profile as profile_models


class TagBase(profile_models.ItemBase):
    class Meta(profile_models.ItemBase.Meta):
        abstract = True

    def __str__(self):
        return str(self.label)


class Skill(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='skill',
    )


class Interest(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='interest',
    )


class Cause(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='cause',
    )
    external_link = models.URLField(
        blank=True,
        verbose_name='external link',
    )

profile/templates/profile/partials/content.html
{% load static %}

{% with contents=profile.contents.all %}
{% if contents %}

<ul id="contents" class="ps-0">
  {% for content in contents %}
  {% with item=content.item %}
  <li class="card mb-3 overflow-x-scroll" data-id="{{ content.pk }}" id="content{{ content.pk }}">
    <div class="card-body p-2 d-flex justify-content-between align-items-center">
      <div class="card-text ms-2 me-auto overflow-auto w-100">
        {{ item.render|safe }}
        {% with attached=content.subcontents.all %}
        {% if attached %}
        <ul id="attachments{{ content.pk }}" class="list-group list-group-flush">
          {% for att in attached %}
          <li class="list-group-item" data-id="{{ att.pk }}" id="attached{{ att.pk }}">
            <div class="d-flex justify-content-between align-items-center">
              <div class="me-auto overflow-auto w-100">
                {{ att.item.render }}
              </div>

              {% if request.user == profile.user %}
              <div class="align-self-start me-1 btn-group dropdown-start">
                <button type="button" class="me-2 btn btn-sm btn-outline-light border border-0 rounded" data-bs-toggle="dropdown" aria-expanded="false">
                  <svg width="16" height="16" class="bi">
                    <use href="{% static 'svg_spiritsheet.svg' %}#three-dots"></use>
                  </svg>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a
                            href="{% url 'profile_content_update' profile.pk item.model_name|lower item.pk %}"
                            class="dropdown-item"
                            role="button"
                            title="Edit">
                      <svg class="bi" width="16" height="16">
                        <use href="{% static 'svg_spiritsheet.svg' %}#pencil-square"></use>
                      </svg>
                      Edit
                    </a>
                  </li>
                  <li>
                    <form
                            method="post"
                            onsubmit="return confirm('Are you sure you wish to delete this from your profile?');"
                            action="{% url 'content_content_delete' profile.pk att.pk %}">
                      <button class="dropdown-item btn btn-link link-danger" type="submit" value="deleted" title="Delete">
                        <svg class="bi text-danger" width="16" height="16" fill="currentColor">
                          <use href="{% static 'svg_spiritsheet.svg' %}#trash"></use>
                        </svg>
                        Delete
                      </button>
                      {% csrf_token %}
                    </form>
                  </li>
                </ul>

                {% if contents|length != 1 %}
                <div class="attachmenthandle{{ content.pk }} grabbable d-flex align-items-center"> <!-- d-flex align-items-center justify-content-center mb-1"> -->
                  <svg class="bi" width="16" height="16">
                    <use href="{% static 'svg_spiritsheet.svg' %}#arrows-expand"></use>
                  </svg>
                </div>
                {% endif %}
              </div>
              {% endif %}
            </div>
          </li>
          {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
      </div>

      {% if request.user == profile.user %}
      <div class="align-self-start me-1 btn-group dropdown-start">
        <button type="button" class="me-2 btn btn-sm btn-outline-light border border-0 rounded" data-bs-toggle="dropdown" aria-expanded="false">
            <svg width="16" height="16" class="bi">
                <use href="{% static 'svg_spiritsheet.svg' %}#three-dots"></use>
            </svg>
        </button>
        <ul class="dropdown-menu">
          <li>
            <a
                    href="{% url 'profile_content_update' profile.pk item.model_name|lower item.pk %}"
                    class="dropdown-item"
                    role="button"
                    title="Edit">
              <svg class="bi" width="16" height="16">
                  <use href="{% static 'svg_spiritsheet.svg' %}#pencil-square"></use>
              </svg>
              Edit
            </a>
          </li>
          <li>
            <a
                    href="{% url 'content_content_select' profile.pk content.pk %}"
                    class="dropdown-item" {# btn btn-sm btn-outline-light border border-0 rounded #}
                    title="Attach content">
              <svg class="bi" width="16" height="16">
                  <use href="{% static 'svg_spiritsheet.svg' %}#file-earmark-plus"></use>
              </svg>
              Attach content
            </a>
          </li>
          <li>
            <form
                    method="post"
                    onsubmit="return confirm('Are you sure you wish to delete this from your profile?');"
                    action="{% url 'profile_content_delete' profile.pk item.model_name|lower content.pk %}">
              <button class="dropdown-item btn btn-link link-danger" type="submit" value="deleted" title="Delete">
                <svg class="bi text-danger" width="16" height="16" fill="currentColor">
                    <use href="{% static 'svg_spiritsheet.svg' %}#trash"></use>
                </svg>
                Delete
              </button>
              {% csrf_token %}
            </form>
          </li>
        </ul>

        {% if contents|length != 1 %}
        <div class="contenthandle grabbable d-flex align-items-center"> <!-- d-flex align-items-center justify-content-center mb-1"> -->
          <svg class="bi" width="16" height="16">
              <use href="{% static 'svg_spiritsheet.svg' %}#arrows-expand"></use>
          </svg>
        </div>
        {% endif %}
      </div>
      {% endif %}
    </div>
  </li>
  {% endwith %}
  {% endfor %}
</ul>

{% else %}
<div class="card-body">
  <p class="card-text">There's no content in this profile yet</p>
</div>
{% endif %}
{% endwith %}

profile/templates/profile/partials/header.html
<div id="FN" class="fs-2 fw-bold mb-0">{{ profile.fn }}</div>

{% with headline=profile.headline %}
{% if headline %}
<div id="headline" class="mb-0">{{ headline }}</div>
{% else %}
<div class="mb-1 px-1 border rounded text-muted" style="max-width: 350px;">Headline</div>
{% endif %}
{% endwith %}

{% with nick=profile.nickname loc=profile.location %}
<div class="d-flex justify-content-start mb-0">
  {% if loc %}
  <div id="location" class="fs-6 text-muted">{{ loc }}</div>
  {% endif %}
  {% if nick and loc %}
  <div class="fs-6 text-muted mx-2"> &#x2022; </div>
  {% endif %}
  {% if nick %}
  <div id="NICKNAME" class="fs-6 text-muted">"{{ nick }}"</div>
  {% endif %}
</div>
{% endwith %}

{% with description=profile.about %}
{% if description %}
<p class="d-flex flex-wrap mt-4 mb-0">{{ description|linebreaksbr }}</p>
{% endif %}
{% endwith %}

profile/templates/profile/partials/pagination.html
<div class="pagination">
    <ul class="pagination justify-content-center">
        {% if page.has_previous %}
        <li class="page-item">
            <a href="?page={{ page.previous_page_number }}" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">Previous</a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link">{{ page.number }}</a>
        </li>
        {% if page.has_next %}
        <li class="page-item">
            <a href="?page={{ page.next_page_number }}" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">Next</a>
        </li>
        {% endif %}
    </ul>
</div>

profile/templates/profile/partials/photo.html
{% load thumbnail %}
{% with profimg=profile.photo %}
{% thumbnail profimg "200x200" crop="center" as im %}
<img id="PHOTO" class="rounded" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ profile.card.FN }} profile photo">
{% empty %}
<svg class="rounded" width="200" height="200" xmlns="http://www.w3.org/2000/svg">
  <rect width="200" height="200" fill="gray" />
</svg>
{% endthumbnail %}
{% endwith %}

profile/templates/profile/partials/preview_card.html
{% load static %}
{% load thumbnail %}
<div class="card me-3 mb-3" style="width:{{ card_width|default:28 }}rem">
    <div class="card-header">
        <a href="{{ profile.get_absolute_url }}" class="text-reset text-decoration-none">
            <h4 class="mb-1 card-title">{{ profile.title }}</h4>
            <p class="card-subtitle text-muted">Kind: {{ profile.get_kind_display }}</p>
            {% if profile.description %}
            <div class="mt-2 card-text">
                {{ profile.description }}
            </div>
            {% endif %}
        </a>

        <div class="position-absolute top-0 end-0 btn-group">
            <button type="button" class="me-1 btn btn-sm btn-outline-light border border-0 rounded" data-bs-toggle="dropdown" aria-expanded="false">
                <svg width="16" height="16" class="bi">
                    <use href="{% static 'svg_spiritsheet.svg' %}#three-dots"></use>
                </svg>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
                <li>
                    <a
                            href="{% url 'list_profile_edit' profile.pk %}"
                            class="dropdown-item"
                            role="button"
                            title="Edit">
                        <svg class="bi" width="16" height="16">
                            <use href="{% static 'svg_spiritsheet.svg' %}#pencil-square"></use>
                        </svg>
                        Edit
                    </a>
                </li>
                <li>
                    <form
                            method="post"
                            onsubmit="return confirm('Are you sure you wish to delete your {{ profile.title }} profile?');"
                            action="{% url 'profile_delete' profile.pk %}">
                        <button class="dropdown-item" type="submit" value="deleted" title="Delete">
                            <svg class="bi text-danger" width="16" height="16" fill="currentColor">
                                <use href="{% static 'svg_spiritsheet.svg' %}#trash"></use>
                            </svg>
                            Delete
                        </button>
                        {% csrf_token %}
                    </form>
                </li>
            </ul>
        </div>
    </div>

    <div class="card-body">
        <a href="{{ profile.get_absolute_url }}" class="text-reset text-decoration-none">
            <div class="d-flex">
                {% with profimg=profile.photo %}
                {% if profimg %}
                <div class="me-3 d-flex flex-column">
                    {% thumbnail profimg "100x100" crop="center" as im %}
                    <img id="PHOTO" class="rounded" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ profile.card.FN }} profile photo">
                    {% empty %}
                    <svg class="rounded" width="100" height="100" xmlns="http://www.w3.org/2000/svg">
                        <rect width="100" height="100" fill="gray" />
                    </svg>
                    {% endthumbnail %}
                </div>
                {% endif %}
                {% endwith %}

                <div class="justify-content-left flex-wrap">
                    <h5 class="mb-0 card-text">{{ profile.fn }}</h5>
                    {% if profile.headline %}<p class="card-text mb-0">{{ profile.headline }}</p>{% endif %}
                    {% with nick=profile.nickname loc=profile.location %}
                    {% if nick or loc %}
                    <p class="text-muted card-text mb-0">
                        {% if loc %}
                        {{ loc }}
                        {% endif %}

                        {% if nick and loc %}
                        &#x2022;
                        {% endif %}

                        {% if nick %}
                        "{{ nick }}"
                        {% endif %}
                    </p>
                    {% endif %}
                    {% endwith %}
                </div>
            </div>
        </a>
    </div>
</div>

profile/templates/profile/partials/share_profile.html
{% load static %}
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-text">Share your profile</h4>
    </div>
    <div class="modal-body d-flex flex-column align-items-center">
      <p class="card-text">Scan the QR code</p>
      <p>
        {{ qr_svg|safe }}
      </p>
      <p class="card-text">or copy this link to share.</p>
      <div class="d-inline-flex user-select-all">
        <span
                class="text-body px-1"
                style="cursor: pointer;"
                onclick="copyTextToClipboard('shareLink{{ link.pk }}')"
                tabindex="0"
                data-bs-container="body"
                data-bs-toggle="popover"
                data-bs-trigger="focus"
                data-bs-placement="top"
                data-bs-content="Link copied"
        >
          <svg width="16" height="16" class="bi" fill="currentColor">
            <use href="{% static 'svg_spiritsheet.svg' %}#copy"></use>
          </svg>
        </span>
        <span id="shareLink{{ link.pk }}" class="border rounded m-0 px-1">
          {{ link.get_shareable_url }}
        </span>
      </div>
    </div>
    <div class="modal-footer justify-content-between">
      <p class="card-text">
        <a href="{% url 'profile_link_detail' link.profile.pk link.pk %}">
          {{ link.label }}
          link info
        </a>
      </p>
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    </div>
  </div>
</div>
<script src="{% static 'js/copy_to_clip.js' %}"></script>
<script>
  $( document ).ready(function() {
    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
    const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
  });
</script>