contacts/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from profile import views as prof_views

urlpatterns = [
    path('', prof_views.home, name='home'),
    path('account/', prof_views.account, name='account'),
    path(
        'account/',
        include([
            path('login/', prof_views.LoginView.as_view(), name='login'),
            path('', include('django.contrib.auth.urls'))
        ]),
    ),
    path('account/register/', prof_views.register, name='register'),
    path(
        'content/',
        include([
            path('', prof_views.user_content_view, name='content'),
            path('new/', prof_views.add_item, name='add_item'),
            path(  # for single models like Email or WorkExperience
                '<slug:model_name>/',
                include([
                    path('new/', prof_views.ContentCreateUpdateView.as_view(), name='item_create'),
                    path('<int:content_pk>/', prof_views.ContentCreateUpdateView.as_view(), name='item_update'),
                    path('<int:content_pk>/delete/', prof_views.content_delete, name='item_delete'),
                ])
            ),
        ]),
    ),
    path('shared/<uuid:uid>/', prof_views.SharedProfileView.as_view(), name='shared_profile'),
    path(
        'connections/',
        include([
            path('', prof_views.ConnectionListView.as_view(), name='connection_list'),
            path('declined/', prof_views.DeclinedListView.as_view(), name='declined_list'),
            path('<int:connection_pk>/', prof_views.connection, name='connection'),
            path('<int:request_pk>/accept/', prof_views.connection_accept, name='connection_accept'),
            path('<int:request_pk>/decline/', prof_views.connection_decline, name='connection_decline'),
        ])
    ),

    path('admin/', admin.site.urls),
    path('profile/', include('profile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.profile_list, name='profile_list'),
    path('new/', views.ProfileCreateUpdateView.as_view(), {'next': 'profile'}, name='profile_create'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('content/<int:related_content_pk>/order', views.ContentOrderView.as_view(), name='attachment_order'),
    path(
        'edit/<int:profile_pk>/',
        views.ProfileCreateUpdateView.as_view(),
        {'next': 'profile_list'},
        name='list_profile_edit'
    ),
    # consider [Sqids](https://sqids.org/) instead of pks
    path(
        '<int:profile_pk>/',
        include([
            path('', views.profile, name='profile'),
            path('edit/', views.ProfileCreateUpdateView.as_view(), {'next': 'profile'}, name='profile_edit'),
            path('delete/', views.profile_delete, name='profile_delete'),
            path('select/', views.ProfileSelectContentView.as_view(), name='profile_content_select', ),
            path('editdetail/', views.ProfileDetailEditView.as_view(), name='profile_detail_edit'),
            path('img/', views.update_profile_img, name='update_profile_img'),
            path('img/delete/', views.profile_img_delete, name='profile_img_delete'),
            path(
                'share/',
                include([
                    path('', views.share, name='share'),
                    path('<int:link_pk>/', views.share, name='link_share'),
                    path(
                        'links/',
                        include([
                            path('', views.profile_links, name='profile_links'),
                            path('new/', views.ProfileCreateLink.as_view(), name='profile_link_create'),
                            path('<pk>/', views.ProfileLinkDetail.as_view(), name='profile_link_detail'),
                            path('<pk>/delete/', views.profile_link_delete, name='profile_link_delete'),
                        ]),
                    ),
                ]),
            ),
            path(
                '<int:content_pk>/',
                include([
                    path('select/', views.ProfileSelectContentView.as_view(), name='content_content_select'),
                    path('delete/', views.content_delete, name='content_content_delete'),
                ])
            ),
            path(
                '<slug:model_name>/',
                include([
                    path('new/', views.ContentCreateUpdateView.as_view(), name='profile_content_create'),
                    path('<int:content_pk>/', views.ContentCreateUpdateView.as_view(), name='profile_content_update'),
                    path('<int:content_pk>/delete/', views.content_delete, name='profile_content_delete'),
                ]),
            ),
        ]),
    ),
    path(
        'links/',
        include([
            path('', views.profile_links, name='link_list'),
            path('<pk>/', views.ProfileLinkDetail.as_view(), name='link_detail'),
        ])
    ),

    # path('', views.profile_list, name='profile_list'),
    # path('<slug:slug>/', views.profile, name='profile'),
    # path('<slug:slug>/edit/', views.EditCardView.as_view(), name='edit'),

    # path('share/', views.share_card, name='share'),
    # path('share/<uuid:share_uuid>/', views.view_shared_profile, name='shared_profile'),
    # path('share/<uuid:share_uuid>/connect/', views.connect, name='connect'),

    # path('download/', views.download_card, name='download_card'),
    # path('connections/', views.connection_list, name='connection_list'),
    # path('connections/<uuid:connection_id>/', views.connection_detail, name='connection_detail'),
    # path('contactbook/', views.contact_book, name='contact_book'),
    # path('contactbook/import', views.import_cards, name='import_cards'),
    # path('contactbook/<int:card_id>', views.card_detail, name='card_detail'),
    # path('connections/edit/', views.edit_connection, name='edit_connection'),
    # path('connections/edit/<uuid:connection_id>/', views.edit_connection, name='edit_connection'),
    # path('connections/download/<uuid:connection_id>/', views.download_card, name='download_connection_card')
]

profile/models.py
import uuid
import os.path
import vobject
import datetime as dt
from urllib.parse import urlparse

from .fields import OrderField
from .utils import consts, vcard

from django.apps import apps
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models import Value
from django.http import HttpResponse
from django.utils.text import slugify
from embed_video.fields import EmbedVideoField
from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _
from djangoyearlessdate.models import YearlessDateField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation


class Profile(models.Model):
    class Kind(models.TextChoices):
        INDIVIDUAL = 'ID', _('Individual')

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    # individual, group, org...
    kind = models.CharField(
        max_length=2,
        choices=Kind,
        default=Kind.INDIVIDUAL,
        blank=False,
        verbose_name='kind',
    )

    # -------- local info for the user --------
    title = models.CharField(max_length=50, blank=False, verbose_name='kind')
    description = models.CharField(blank=True, verbose_name='description')

    # -------- info displayed on profile --------
    # todo: update for non-individual self.kind
    prefix = models.CharField(max_length=50, blank=True, verbose_name='prefix')
    first_name = models.CharField(max_length=50, blank=True, verbose_name='first name')
    middle_name = models.CharField(max_length=50, blank=True, verbose_name='middle name')
    # last name serves as name if kind is not individual
    last_name = models.CharField(max_length=50, blank=True, verbose_name='last name')
    suffix = models.CharField(max_length=50, blank=True, verbose_name='suffix')
    nickname = models.CharField(max_length=50, blank=True, verbose_name='nickname')

    photo = models.ImageField(
        upload_to=consts.PROFILE_PHOTO_DIR,
        blank=True,
        verbose_name='photo',
    )

    headline = models.CharField(max_length=120, blank=True, verbose_name='headline')
    location = models.CharField(max_length=50, blank=True, verbose_name='location')
    about = models.TextField(blank=True, verbose_name='about')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return f'{self.user.username}\'s {self.title} Profile'

    def get_absolute_url(self):
        return reverse('profile', kwargs={'profile_pk': self.pk})

    @property
    def fn(self):
        s = (f'{self.prefix + " " if self.prefix else ""}'
             f'{self.first_name + " " if self.first_name else ""}'
             f'{self.middle_name + " " if self.middle_name else ""}'
             f'{self.last_name}'
             f'{", " + self.suffix if self.suffix else ""}')
        return s


class Content(models.Model):
    profile = models.ForeignKey(
        Profile,
        related_name='contents',
        related_query_name='content',
        on_delete=models.CASCADE,
    )

    def item_subclass_choices(self):
        return [m.__name__ for m in apps.get_models() if issubclass(m, ItemBase)]

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={
            'model__in': item_subclass_choices()
        }
    )
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['profile'])

    class Meta:
        ordering = ['order']
        verbose_name = 'content'
        verbose_name_plural = 'contents'


class ItemBase(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='%(class)s_related',
        on_delete=models.CASCADE,
    )
    content_related = GenericRelation(Content)
    label = models.CharField(max_length=50, blank=True, verbose_name='label')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def render(self):
        return render_to_string(
            f'profile/partials/models/{self.__class__.__name__.lower()}_render.html',
            {'object': self}
        )


# todo: validate all Items
class ContactInfoBase(ItemBase):
    class InfoTypes(models.TextChoices):
        WORK = 'W', _('Work')
        HOME = 'H', _('Home')
        OTHER = 'O', _('Other')

    info_type = models.CharField(
        max_length=1,
        choices=InfoTypes,
        blank=True,
        verbose_name='type',
    )

    class Meta(ItemBase.Meta):
        abstract = True


class Email(ContactInfoBase):
    email_address = models.EmailField(
        blank=False,
        verbose_name='email',
    )

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'email'
        verbose_name_plural = 'emails'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.email_address}'
                f'{", " + self.label if self.label else ""}')


class Phone(ContactInfoBase):
    # todo: international?
    phone_number = PhoneNumberField(
        balnk=False,
        verbose_name='phone number',
    )

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'phone'
        verbose_name_plural = 'phones'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.phone_number}'
                f'{", " + self.label if self.label else ""}')


class Address(ContactInfoBase):
    # todo: international?
    street1 = models.CharField(blank=False, verbose_name='street')
    street2 = models.CharField(blank=True, verbose_name='street line 2')
    city = models.CharField(blank=False, verbose_name='city')
    state = models.CharField(blank=False, verbose_name='state')
    zip = models.CharField(max_length=10, blank=False, verbose_name='zip code')
    country = models.CharField(blank=True, verbose_name='country')

    class Meta(ContactInfoBase.Meta):
        verbose_name = 'address'
        verbose_name_plural = 'addresses'

    def __str__(self):
        return (f'{self.info_type.label + ": " if self.info_type else ""}'
                f'{self.street1}'
                f'{", " + self.label if self.label else ""}')


class LinkBase(models.Model):
    """holds primary domains and info for external links
    E.g. netloc: https://github.com/"""
    title = models.CharField(
        blank=False,
        default='Website',
        verbose_name='title',
    )
    netloc = models.CharField(
        blank=True,
        verbose_name='netloc',
    )

    class Meta:
        verbose_name = 'linkbase'
        verbose_name_plural = 'linkbases'

    def __str__(self):
        return str(self.title)


class Link(ItemBase):
    linkbase = models.ForeignKey(
        LinkBase,
        default=1,
        on_delete=models.SET_DEFAULT,
        verbose_name='linkbase',
        related_name='links',
        related_query_name='link',
    )
    url = models.CharField(max_length=200, verbose_name='url')
    is_independent_url = models.BooleanField(
        default=True,
        blank=False,
        verbose_name='independent url',
        help_text='Indicates url does not require linkbase.netlock as the prefix',
    )

    class Meta(ItemBase.Meta):
        ordering = ['linkbase']
        verbose_name = 'link'
        verbose_name_plural = 'links'

    def __str__(self):
        if self.is_independent_url:
            return str(self.url)
        else:
            return f'{self.linkbase.domain}{self.url}'

    def save(self, *args, **kwargs):
        if not self.is_independent_url:
            self.is_independent_url = self.linkbase == 1
        super().save(*args, **kwargs)

    @property
    def pretty_url(self):
        if self.is_independent_url:
            url = urlparse(str(self.url))
        else:
            url = urlparse(f'{self.linkbase.domain}{self.url}')
        return f'{url.netloc}{url.path}{url.params}{url.query}{url.fragment}'.rstrip('/')


class Attachment(ItemBase):
    class AttachmentTypes(models.TextChoices):
        DOCUMENT = 'D', _('Document')
        IMAGE = 'I', _('Image')

    attachment_type = models.CharField(
        max_length=1,
        choices=AttachmentTypes,
        blank=False,
        verbose_name='attachment type',
    )
    url = models.URLField(
        blank=True,
        verbose_name='url',
    )
    file = models.FileField(
        upload_to=consts.ATTACHMENT_MODEL_DIR,
        blank=True,
        verbose_name='file',
    )

    def __str__(self):
        return (f'{self.attachment_type.label}: '
                f'{self.url if self.url else self.file.name}')


class PostBase(ItemBase):
    title = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='title',
    )
    description = models.TextField(
        blank=True,
        verbose_name='description',
    )
    date = models.DateField(
        blank=True,
        verbose_name='date',
    )
    external_link = models.URLField(
        blank=True,
        verbose_name='external link',
    )

    class Meta(ItemBase.Meta):
        abstract = True
        ordering = ['-date']

    def __str__(self):
        return f'{self.title}{" - " + str(self.date) if self.date else ""}'


class OrgBase(PostBase):
    organization = models.CharField(
        max_length=200,
        blank=True,
        verbose_name='organization',
    )

    class Meta(PostBase.Meta):
        abstract = True

profile/models/tag.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from . import profile as profile_models


class TagBase(profile_models.ItemBase):
    class Meta(profile_models.ItemBase.Meta):
        abstract = True

    def __str__(self):
        return str(self.label)


class Skill(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='skill',
    )


class Interest(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='interest',
    )


class Cause(TagBase):
    label = models.CharField(
        max_length=200,
        blank=False,
        verbose_name='cause',
    )
    external_link = models.URLField(
        blank=True,
        verbose_name='external link',
    )

profile/templates/profile/partials/models/address_render.html
{% extends 'profile/partials/models/model_render.html' %}
{% block objtxt %}
<div class="column">
    {% with lab=object.label tp=object.get_info_type_display %}
    {% if lab or tp %}
    <span class="text-muted">
        {% if tp %}({{ tp }}){% endif %}
    </span>{{ lab }}<br/>
    {% endif %}
    {% endwith %}
    {{ object.street1 }}<br/>
    {% if object.street2 %}{{ object.street2 }}<br>{% endif %}
    {{ object.city }}, {{ object.state }} {{ object.zip }}<br>
    {% if object.country %}{{ object.country }}{% endif %}
</div>
{% endblock %}

profile/templates/profile/partials/models/attachment_render.html
{% extends 'profile/partials/models/model_render.html' %}
{% load static %}
{% load thumbnail %}
{% block objtxt %}

{% with lab=object.label %}
{% with mt=object.model_type %}
{% if mt == 'i' %}
{% if object.url %}
{% thumbnail object.url '200x200' crop='center' as im %}
<figure class="mb-0">
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ lab }}" class="rounded"/>
    {% if lab %}<figcaption>{{ lab }}</figcaption>{% endif %}
</figure>
{% endthumbnail %}
{% else %}
{% thumbnail object.file '200x200' crop='center' as im %}
<figure class="mb-0>
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ object.label }}" class="rounded"/>
    {% if lab %}<figcaption>{{ lab }}</figcaption>{% endif %}
</figure>
{% endthumbnail %}
{% endif %}

{% elif mt == 'd' %}
{% if object.file %}
<span><a href="{{ object.file.url }}" target="_blank">
    {% if lab %}{{ lab }}{% else %}{{ object.filename|truncatechars:100 }}{% endif %}
    <svg width="12" height="12" class="bi" fill="currentColor">
        <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
    </svg>
</a></span>
{% else %}
<span><a href="{{ object.url }}" target="_blank">
    {% if lab %}{{ lab }}{% else %}{{ object.url }}{% endif %}
    <svg width="12" height="12" class="bi" fill="currentColor">
        <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
    </svg>
</a></span>
{% endif %}

{% else %}
{{ object.url }}{{ object.file }}{% if object.label %} - {{ object.label }}{% endif %}
{% endif %}
{% endwith %}
{% endwith %}

{% endblock %}

profile/templates/profile/partials/models/award_render.html
{% extends "profile/partials/models/postbase_render.html" %}

{% block postcontent %}

{% with org=object.organization link=object.external_link %}
{% if org or link %}
<p class="card-text">
    {% if org and link %}
    <a href="{{ link }}">{{ org }}</a>
    {% else %}
    {% if org %}{{ org }}{% endif %}
    {% if link %}{{ link|urlize }}{% endif %}
    {% endif %}
</p>
{% endif %}
{% endwith %}

{% endblock %}

profile/templates/profile/partials/models/education_render.html
{% extends "profile/partials/models/membershipbase_render.html" %}

{% block posttitle %}
{{ object.label }}{% if object.degree_type %}, {{ object.degree_type }}{% endif %}
{% endblock %}

{% block postcontent %}
{% if object.gpa %}
<p class="text-muted mb-1">{{ object.gpa }} GPA</p>
{% endif %}
{% endblock %}

profile/templates/profile/partials/models/email_render.html
{% extends 'profile/partials/models/model_render.html' %}
{% block objtxt %}
<div class="column">
    {% with tp=object.get_info_type_display lab=object.label %}
    {% if tp %}<span class="text-muted">({{ tp }})</span>{% endif %}
    {{ object.email_address|urlize }}
    {% if lab %}
    <p class="mb-0">
        {% if lab %}{{ lab }}{% endif %}
    </p>
    {% endif %}
    {% endwith %}
</div>
{% endblock %}

profile/templates/profile/partials/models/link_render.html
{% extends 'profile/partials/models/model_render.html' %}
{% load static %}
{% block objtxt %}
<div class="column">
    <a href="{{ object }}" target="_blank">
        {% if object.model_name == 'Website' %}
        {{ object }}
        <svg width="12" height="12" class="bi" fill="currentColor">
            <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
        </svg>
        {% else %}
        @{{ object.url }}
        {% endif %}
    </a>
    {% if object.label %}<p class="mb-0">{{ object.label }}</p>{% endif %}
</div>
{% endblock %}

profile/templates/profile/partials/models/media_render.html
{% load thumbnail %}
{% with lab=object.label %}
{% with mt=object.media_type %}
{% if mt == 'IMG' %}
{% if object.url %}
{% thumbnail object.url '200x200' crop='center' as im %}
<figure>
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ lab }}" class="rounded"/>
    {% if lab %}<figcaption>{{ lab }}</figcaption>{% endif %}
</figure>
{% endthumbnail %}
{% else %}
{% thumbnail object.file '200x200' crop='center' as im %}
<figure>
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ object.label }}" class="rounded"/>
    {% if lab %}<figcaption>{{ lab }}</figcaption>{% endif %}
</figure>
{% endthumbnail %}
{% endif %}

{% elif mt == 'DOC' %}
Document:
{% if object.file %}
<a href="{{ object.file.url }}" target="_blank">
    {% if lab %}{{ lab }}{% else %}{{ object.file }}{% endif %}
</a>
{% else %}
<a href="{{ object.url }}" target="_blank">
    {% if lab %}{{ lab }}{% else %}{{ object.url }}{% endif %}
</a>
{% endif %}

{% else %}
{{ object.get_media_type_display }}: {{ object.url }}{{ object.file }}{% if object.label %} - {{ object.label }}{% endif %}
{% endif %}
{% endwith %}
{% endwith %}

profile/templates/profile/partials/models/membershipbase_render.html
{% extends "profile/partials/models/postbase_render.html" %}
{% load static %}
{% block postlink %}

{% if object.employment_type %}
<p class="mb-1">{{ object.get_employment_type_display }}</p>
{% endif %}

{% with org=object.organization link=object.external_link loc=object.location ws=object.get_work_setting_display %}
{% if org or link or loc %}
<p class="mb-1">
    {% if org and link %}
    <a href="{{ link }}">
        {{ org }}
        <svg width="12" height="12" class="bi" fill="currentColor">
            <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
        </svg>
    </a>
    {% else %}
    {% if org %}<span class="text-muted">{{ org }}</span>{% endif %}
    {% if link %}
    <a href="{{ link }}" target="_blank">
        {{ link|truncatechars:35 }}
        <svg width="12" height="12" class="bi" fill="currentColor">
            <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
        </svg>
    </a>
    {% endif %}
    {% endif %}

    {% if loc %}
    <span class="text-muted">| {{ loc }}</span>
    {% endif %}
    {% if ws %}
    <span class="text-muted">| {{ ws }}</span>
    {% endif %}
</p>
{% endif %}
{% endwith %}

{% endblock %}

profile/templates/profile/partials/models/model_render.html
{% load static %}
<div class="d-flex align-items-start">
    <p class="mb-0">
        <svg width="16" height="16" class="bi me-3">
            <use href="{% static 'svg_spiritsheet.svg' %}#{{ object.model_name|lower }}"></use>
        </svg>
    </p>
    {% block objtxt %}
    {{ object }}
    {% endblock %}
</div>

profile/templates/profile/partials/models/orgbase_render.html
{% extends "profile/partials/models/postbase_render.html" %}
{% load static %}
{% block postlink %}

{% with org=object.organization link=object.external_link %}
{% if org or link %}
<p class="mb-1">
    {% if org and link %}
    <a href="{{ link }}" target="_blank">
        {{ org }}
        <svg width="12" height="12" class="bi" fill="currentColor">
            <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
        </svg>
    </a>
    {% else %}
    {% if org %}{{ org }}{% endif %}
    {% if link %}
    <a href="{{ link }}" target="_blank">
        {{ link|truncatechars:35 }}
        <svg width="12" height="12" class="bi" fill="currentColor">
            <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
        </svg>
    </a>
    {% endif %}
    {% endif %}
</p>
{% endif %}
{% endwith %}

{% endblock %}

profile/templates/profile/partials/models/patent_render.html
{% extends "profile/partials/models/postbase_render.html" %}
{% load static %}
{% block postdate %}{% endblock %}

{% block postcontent %}

{% with no=object.number co=object.country %}
{% if no or co %}
<h6 class="mb-1">
    {% if no %}
    {{ no }}
    {% endif %}
    {% if co %}
    ({{ co }})
    {% endif %}
</h6>
{% endif %}
{% endwith %}

{% if object.contributors %}
<p class="mb-1 fw-bold">Inventors: {{ object.contributors }}</p>
{% endif %}

{% if object.source %}
<p class="mb-1">Assignee: <span class="fst-italic">{{ object.source }}</span></p>
{% endif %}

{% if object.external_link %}
<p class="mb-1"><a href="{{ object.external_link }}" target="_blank" class="mb-1">
    {{ object.external_link }}
    <svg width="12" height="12" class="bi" fill="currentColor">
        <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
    </svg>
</a></p>
{% endif %}

<p class="mb-3"></p>

{% if object.status %}
<p class="mb-1">Status: <span class="fst-italic">{{ object.get_status_display }}</span></p>
{% endif %}

{% if object.date %}
<p class="mb-1">{{ object.date }} <span class="fw-light">- Issued</span></p>
{% endif %}
{% if object.filing_date %}
<p class="mb-1">{{ object.filing_date }} <span class="fw-light">- Application filed</span></p>
{% endif %}

<p class="mb-3"></p>

{% if object.classifications %}
<p class="mb-2">Classifications: <span class="fst-italic">{{ object.classifications }}</span></p>
{% endif %}

{% endblock %}

{% block postlink %}{% endblock %}

profile/templates/profile/partials/models/phone_render.html
{% extends 'profile/partials/models/model_render.html' %}
{% block objtxt %}
<div class="">
    {% with tp=object.get_info_type_display lab=object.label %}
    {% if tp or lab %}
    <span class="text-muted">
        {% if tp %}({{ tp }}){% endif %}
        {{ lab }}
    </span>
    {% endif %}
    {% endwith %}
    {{ object.phone_number }}
</div>
{% endblock %}

profile/templates/profile/partials/models/postbase_render.html
{% load static %}
{% load profile_extras %}
<div class="mb-0">
    <h5 class="mb-1">
        {% block posttitle %}
        {{ object.label }}
        {% endblock %}
    </h5>

    {% block postdate %}
    {% if object.date or object.end_date %}
    <p class="mb-1">
        {% if object.date %}
        {{ object.date }}

        {% if object.end_date %}
        - {{ object.end_date }}
        {% else %}
        {% if object.current %} - Present{% endif %}
        {% endif %}

        {% else %}
        {{ object.end_date }}
        {% endif %}
    </p>
    {% endif %}
    {% endblock %}

    {% block postcontent %}{% endblock %}

    {% block postlink %}
    {% if object.external_link %}
    <p class="mb-1">
        {{ object.external_link|urlizetrunc:35 }}
        <svg width="12" height="12" class="bi" fill="currentColor">
            <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
        </svg>
    </p>
    {% endif %}
    {% endblock %}

    {% if object.description %}
    {{ object.description|markdown|linebreaks }}
    {% endif %}
</div>

profile/templates/profile/partials/models/projectbase_render.html
{% extends "profile/partials/models/postbase_render.html" %}
{% load static %}
{% block postcontent %}

<div class="mb-1">
    {% if object.contributors %}
    <p class="fw-bold mb-1">{{ object.contributors }}</p>
    {% endif %}

    {% with s=object.source link=object.external_link %}
    {% if s or link %}
    <p class="fst-italic mb-1">
        {% if s and link %}
        <a href="{{ link }}">
            {{ s }}
            <svg width="12" height="12" class="bi" fill="currentColor">
                <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
            </svg>
        </a>
        {% else %}
        {% if s %}{{ s }}{% endif %}
        {% if link %}
        <a href="{{ link }}">
            {{ link }}
            <svg width="12" height="12" class="bi" fill="currentColor">
                <use href="{% static 'svg_spiritsheet.svg' %}#box-arrow-up-right"></use>
            </svg>
        </a>
        {% endif %}
        {% endif %}
    </p>
    {% endif %}
    {% endwith %}
</div>

{% if object.affiliated_institutions %}
<p class="mb-1">Affiliated Institutions: {{ object.affiliated_institutions }}</p>
{% endif %}

{% if object.funding_source %}
<p class="mb-1">Funding from: {{ object.funding_source }}</p>
{% endif %}

{% endblock %}

{% block postlink %}{% endblock %}